{
	"version": 1746837069,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bird-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/background-sheet0.png",
		"images/bottompipe-sheet0.png",
		"images/toppipe-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bird2-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/redlose-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/pax let's make a game death.m4a",
		"media/pax let's make a game death.ogg",
		"media/pax let's make a game teeth.m4a",
		"media/pax let's make a game teeth.ogg",
		"media/pax let's make a game.m4a",
		"media/pax let's make a game.ogg",
		"media/pax let's make a game flap.m4a",
		"media/pax let's make a game flap.ogg",
		"media/pax let's make a game flap2.m4a",
		"media/pax let's make a game flap2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}