{
	"version": 1787456226,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"media/car loop.m4a",
		"media/car loop.ogg",
		"media/car turns - 01.m4a",
		"media/car turns - 01.ogg",
		"media/car turns - 02.m4a",
		"media/car turns - 02.ogg",
		"media/car turns - 03.m4a",
		"media/car turns - 03.ogg",
		"media/car turns - 04.m4a",
		"media/car turns - 04.ogg",
		"media/escapeothy - 01.m4a",
		"media/escapeothy - 01.ogg",
		"media/escapeothy - 02.m4a",
		"media/escapeothy - 02.ogg",
		"media/game start - 01.m4a",
		"media/game start - 01.ogg",
		"media/game start - 02.m4a",
		"media/game start - 02.ogg",
		"media/game start - 03.m4a",
		"media/game start - 03.ogg",
		"media/run jimmothy - 01.m4a",
		"media/run jimmothy - 01.ogg",
		"media/run jimmothy - 02.m4a",
		"media/run jimmothy - 02.ogg",
		"media/run jimmothy - 03.m4a",
		"media/run jimmothy - 03.ogg",
		"media/run jimmothy - 04.m4a",
		"media/run jimmothy - 04.ogg",
		"media/squishothy - 01.m4a",
		"media/squishothy - 01.ogg",
		"media/squishothy - 02.m4a",
		"media/squishothy - 02.ogg",
		"media/squishothy - 03.m4a",
		"media/squishothy - 03.ogg",
		"media/squishothy - 04.m4a",
		"media/squishothy - 04.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}